-- Create Feedback Table
create table public.feedback (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  project_name text not null,
  content text not null,
  status text not null default 'new' check (status in ('new', 'in-progress', 'resolved')),
  urgency text not null default 'medium' check (urgency in ('low', 'medium', 'high'))
);

-- Create Notes Table
create table public.notes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text, -- HTML/JSON from Tiptap
  folder_id bigint references public.folders(id)
);

-- Create Folders Table
create table public.folders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null
);

-- Enable Row Level Security (RLS)
alter table public.feedback enable row level security;
alter table public.notes enable row level security;
alter table public.folders enable row level security;

-- Create Policy (Allow all for anon for demo purposes - REPLACE IN PROD)
create policy "Enable read access for all users" on public.feedback for select using (true);
create policy "Enable insert access for all users" on public.feedback for insert with check (true);
create policy "Enable read access for all users" on public.notes for select using (true);
create policy "Enable insert access for all users" on public.notes for insert with check (true);
